---
- name: "Push docker images to any docker registry"
  hosts: local
  become: yes
  vars_files:
    - ["{{inventory_dir}}/secrets.yml"]
  tasks:
    - name: login to registry
      docker_login:
        registry: "{{ vault_docker_registry_url }}"
        username: "{{ vault_docker_registry_user }}"
        password: "{{ vault_docker_registry_password }}"
      tags: azure
    - block:
        - name: Write GCR service account key to a temporary file
          copy:
            content: "{{ gcp_service_account }}"
            dest: /tmp/gcr_service_account_key.json

        - name: Authenticate Docker to GCR
          command: >
            docker login -u _json_key -p "{{ lookup('file', '/tmp/gcr_service_account_key.json') }}" https://gcr.io
          no_log: true

        - name: Remove temporary GCR service account key file
          file:
            path: /tmp/gcr_service_account_key.json
            state: absent
      tags: gcp

    - block:
        - name: Push image to registry
          docker_image:
            name: "{{ hub_org }}/{{ image_name }}:{{ image_tag }}"
            push: yes
        - file:
            path: "/root/.docker"
            state: absent
      tags: always
